title: Math Defender
url: https://fiverocksgames.github.io
baseurl: /math-defender
markdown: kramdown
collections:
  math_defender_journals:
    output: true
    sort_by: date
defaults:
  - scope:
      path: ""
      type: math_defender_journals
    values:
      layout: math-defender-journal
exclude:
  - README.md
  - PUBLICATION_PROFILE.md
